2020-05-24 00:05:34.860 ERROR 30477 --- [XNIO-1 task-3] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /216.218.206.67:49810
2020-05-24 03:01:05.066 ERROR 30477 --- [XNIO-1 task-6] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /59.167.232.88:35154
2020-05-24 03:16:00.406  WARN 30477 --- [XNIO-1 task-5] l.s.config.RequestAuthorizationFilter    : Authorization missing for 109.234.153.134 on POST /azenv.php
2020-05-24 03:16:05.474 ERROR 30477 --- [XNIO-1 I/O-1] io.undertow.request                      : UT005071: Undertow request failed HttpServerExchange{ CONNECT check.best-proxies.ru:80}

java.lang.IllegalArgumentException: UT000068: Servlet path match failed
	at io.undertow.servlet.handlers.ServletPathMatchesData.getServletHandlerByPath(ServletPathMatchesData.java:83) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:88) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:146) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

2020-05-24 04:44:40.755 ERROR 30477 --- [XNIO-1 task-4] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /80.82.78.104:49608
2020-05-24 05:22:32.529  WARN 30477 --- [XNIO-1 task-7] l.s.config.RequestAuthorizationFilter    : Authorization missing for 162.243.142.176 on GET /hudson
2020-05-24 07:15:50.192  WARN 30477 --- [XNIO-1 task-9] l.s.config.RequestAuthorizationFilter    : Authorization missing for 109.234.153.133 on POST /azenv.php
2020-05-24 07:15:55.264 ERROR 30477 --- [XNIO-1 I/O-2] io.undertow.request                      : UT005071: Undertow request failed HttpServerExchange{ CONNECT check.best-proxies.ru:80}

java.lang.IllegalArgumentException: UT000068: Servlet path match failed
	at io.undertow.servlet.handlers.ServletPathMatchesData.getServletHandlerByPath(ServletPathMatchesData.java:83) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:88) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:146) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

2020-05-24 07:41:45.027  INFO 30477 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "608009300064862224", "sessionId": "6d5a40c30862976f4cfb2db94aee4629", "event": {"token": "2045130113aa6a9e", "guild_id": "608009300064862224", "endpoint": "eu-central533.discord.media:80"}}
2020-05-24 07:41:46.106  INFO 30477 --- [XNIO-1 task-8] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-05-24 07:41:46.817  INFO 30477 --- [lava-daemon-pool-info-loader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: Lovely
2020-05-24 07:41:46.930  INFO 30477 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "608009300064862224", "track": "QAAAhQIAHkJpbGxpZSBFaWxpc2gsIEtoYWxpZCAtIGxvdmVseQANQmlsbGllIEVpbGlzaAAAAAAAAxEoAAtWMVBsOEN6TnpDdwABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PVYxUGw4Q3pOekN3AAd5b3V0dWJlAAAAAAAAAAA=", "noReplace": false, "startTime": "0"}
2020-05-24 07:43:52.575  INFO 30477 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "608009300064862224"}
2020-05-24 07:43:52.577  INFO 30477 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "destroy", "guildId": "608009300064862224"}
2020-05-24 08:21:56.344 ERROR 30477 --- [XNIO-1 task-11] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /87.107.59.130:50706
2020-05-24 08:47:26.647 ERROR 30477 --- [XNIO-1 task-12] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /45.227.255.224:61000
2020-05-24 09:31:30.940 ERROR 30477 --- [XNIO-1 task-13] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /139.162.79.87:41160
2020-05-24 10:41:24.609 ERROR 30477 --- [XNIO-1 task-14] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /116.96.106.252:33382
2020-05-24 10:45:52.189 ERROR 30477 --- [XNIO-1 task-15] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /193.118.53.210:58850
2020-05-24 11:15:45.250  WARN 30477 --- [XNIO-1 task-1] l.s.config.RequestAuthorizationFilter    : Authorization missing for 109.234.153.134 on POST /azenv.php
2020-05-24 11:15:50.312 ERROR 30477 --- [XNIO-1 I/O-1] io.undertow.request                      : UT005071: Undertow request failed HttpServerExchange{ CONNECT check.best-proxies.ru:80}

java.lang.IllegalArgumentException: UT000068: Servlet path match failed
	at io.undertow.servlet.handlers.ServletPathMatchesData.getServletHandlerByPath(ServletPathMatchesData.java:83) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:88) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:146) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

2020-05-24 11:30:18.430  INFO 30477 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:55818 -- CloseStatus[code=1006, reason=]
2020-05-24 11:30:18.433  INFO 30477 --- [XNIO-1 I/O-1] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2020-05-24 11:31:59.163  INFO 30477 --- [XNIO-1 task-16] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:52100
2020-05-24 11:31:59.276  INFO 30477 --- [XNIO-1 task-16] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:52100
2020-05-24 11:35:17.656 ERROR 30477 --- [XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /109.94.119.6:52628
2020-05-24 11:58:17.759  INFO 30477 --- [XNIO-1 I/O-1] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:52100 -- CloseStatus[code=1006, reason=]
2020-05-24 11:58:17.760  INFO 30477 --- [XNIO-1 I/O-1] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2020-05-24 11:58:43.256  INFO 30477 --- [XNIO-1 task-3] l.server.io.HandshakeInterceptorImpl     : Incoming connection from /127.0.0.1:52204
2020-05-24 11:58:43.323  INFO 30477 --- [XNIO-1 task-3] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:52204
2020-05-24 12:22:34.960 ERROR 30477 --- [XNIO-1 task-6] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /85.234.143.114:52678
2020-05-24 12:40:02.320 ERROR 30477 --- [XNIO-1 task-5] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /195.181.88.243:56437
2020-05-24 14:31:58.736  WARN 30477 --- [XNIO-1 task-4] l.s.config.RequestAuthorizationFilter    : Authorization missing for 185.234.217.177 on GET /.git/config
2020-05-24 14:31:58.942  WARN 30477 --- [XNIO-1 task-7] l.s.config.RequestAuthorizationFilter    : Authorization missing for 185.234.217.177 on GET /.env
2020-05-24 14:31:59.150  WARN 30477 --- [XNIO-1 task-9] l.s.config.RequestAuthorizationFilter    : Authorization missing for 185.234.217.177 on GET /sftp-config.json
2020-05-24 14:31:59.356  WARN 30477 --- [XNIO-1 task-8] l.s.config.RequestAuthorizationFilter    : Authorization missing for 185.234.217.177 on GET /.ftpconfig
2020-05-24 14:31:59.563  WARN 30477 --- [XNIO-1 task-10] l.s.config.RequestAuthorizationFilter    : Authorization missing for 185.234.217.177 on GET /.remote-sync.json
2020-05-24 14:31:59.769  WARN 30477 --- [XNIO-1 task-11] l.s.config.RequestAuthorizationFilter    : Authorization missing for 185.234.217.177 on GET /.vscode/ftp-sync.json
2020-05-24 14:31:59.975  WARN 30477 --- [XNIO-1 task-12] l.s.config.RequestAuthorizationFilter    : Authorization missing for 185.234.217.177 on GET /.vscode/sftp.json
2020-05-24 14:32:00.180  WARN 30477 --- [XNIO-1 task-13] l.s.config.RequestAuthorizationFilter    : Authorization missing for 185.234.217.177 on GET /deployment-config.json
2020-05-24 14:32:00.386  WARN 30477 --- [XNIO-1 task-14] l.s.config.RequestAuthorizationFilter    : Authorization missing for 185.234.217.177 on GET /ftpsync.settings
2020-05-24 15:08:05.140 ERROR 30477 --- [XNIO-1 task-15] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /122.228.19.79:5851
2020-05-24 15:15:23.412  WARN 30477 --- [XNIO-1 task-1] l.s.config.RequestAuthorizationFilter    : Authorization missing for 109.234.153.130 on POST /azenv.php
2020-05-24 15:15:28.478 ERROR 30477 --- [XNIO-1 I/O-1] io.undertow.request                      : UT005071: Undertow request failed HttpServerExchange{ CONNECT check.best-proxies.ru:80}

java.lang.IllegalArgumentException: UT000068: Servlet path match failed
	at io.undertow.servlet.handlers.ServletPathMatchesData.getServletHandlerByPath(ServletPathMatchesData.java:83) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:88) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:146) ~[undertow-servlet-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59) ~[undertow-core-2.0.26.Final.jar!/:2.0.26.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66) ~[xnio-api-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561) ~[xnio-nio-3.3.8.Final.jar!/:3.3.8.Final]

